/**
 * The 3D buddy — Agila, through a self-hosted `<model-viewer>`.
 *
 * Build spec T4.1: `<model-viewer>`, bundled by Vite from `node_modules`, never
 * a CDN, so the app works offline. The four stage models are generated by
 * `script/art/build-eagle-glb.mjs` (egg → hatchling → eaglet → flying eagle,
 * each with its own looping clip) and served same-origin from `public/model/`.
 *
 * Two uses. On a card it stands in a three-quarter view and idles. On the map
 * (`is_walker`) it is the Pokémon GO-style avatar: the camera looks down from
 * behind at the map's own pitch, and the model TURNS to face where you walk,
 * eased so a heading change swings rather than snaps.
 */
import "@google/model-viewer";
import { useEffect, useRef, type CSSProperties } from "react";
import { stage_sticker } from "./asset/kit";
import type { Stage } from "./stage.ts";
import { STAGE_LABEL } from "./stage.ts";

/** Stage → model file. Stage keys are the stored ones (`stage.ts`). */
export const STAGE_MODEL: Record<Stage, string> = {
  egg: "/model/agila-egg.glb",
  sprout: "/model/agila-hatchling.glb",
  sapling: "/model/agila-eaglet.glb",
  tree: "/model/agila-eagle.glb",
};

/** You on the map: the trainer (`script/art/build-eagle-glb.mjs`), clips `idle` and `walk`. */
export const TRAINER_MODEL = "/model/agila-trainer.glb";
/**
 * The trainer as a still, rendered from `agila-trainer.glb` itself at the map's
 * idle framing (62° orbit, 28° field of view, turned 24°). It is the poster
 * while the .glb loads, so a cold start shows YOU, not the buddy's egg.
 */
export const TRAINER_POSTER = "/model/agila-trainer-poster.webp";

interface Props {
  stage: Stage;
  /** Render this model instead of the stage's — the map uses it for the trainer. */
  src?: string;
  /** A named clip; the stage models carry one clip each and play it by default. */
  animation?: string;
  /** Stop the clip where it is — the buddy asleep. */
  is_paused?: boolean;
  /** Pixel size of the square viewport. Ignored with `is_fill`. */
  size?: number;
  /** Fill the parent box instead — the Journal tile sizes the viewer, so the
   *  model is not a small square floating in a bigger tile. */
  is_fill?: boolean;
  /** The map avatar: looks down from behind and turns to its heading. */
  is_walker?: boolean;
  is_walking?: boolean;
  /** Degrees clockwise from screen-up — the direction of travel. */
  heading_degree?: number;
}

/** The slice of model-viewer's element API the facing uses (`StagingMixin`). */
type Turntable = HTMLElement & { resetTurntableRotation(theta?: number): void };

/** Three-quarter view when standing still — a face, not a profile. */
const IDLE_YAW = 24;

function isReducedMotion(): boolean {
  return typeof window !== "undefined" && typeof window.matchMedia === "function"
    ? window.matchMedia("(prefers-reduced-motion: reduce)").matches
    : false;
}

export default function CharacterModel({
  stage,
  src,
  animation,
  is_paused = false,
  size = 108,
  is_fill = false,
  is_walker = false,
  is_walking = false,
  heading_degree = 180,
}: Props) {
  const ref = useRef<HTMLElement>(null);
  const yaw = useRef(IDLE_YAW);
  const reduced = isReducedMotion();
  /* Facing: the model looks down +Z, which is screen-down (heading 180). */
  const target = is_walker && is_walking ? 180 - heading_degree : IDLE_YAW;

  useEffect(() => {
    const el = ref.current as Turntable | null;
    if (!el || typeof el.resetTurntableRotation !== "function") return;
    /* Turn the scene pivot, not the `orientation` attribute. A new orientation
       sends model-viewer 4.3.1 through `ARRenderer.onUpdateScene`, which with no
       AR session calls `presentedScene.add` on null and throws before the frame
       is queued — every rAF of a turn. The turntable is the same yaw about Y,
       with no update cycle behind it. */
    const turn = (degree: number) => el.resetTurntableRotation((degree * Math.PI) / 180);
    if (reduced) {
      yaw.current = target;
      turn(target);
      return;
    }
    let frame = 0;
    const tick = () => {
      /* Shortest way round, then a fixed fraction per frame. */
      const delta = ((((target - yaw.current) % 360) + 540) % 360) - 180;
      yaw.current += delta * 0.18;
      turn(yaw.current);
      if (Math.abs(delta) > 0.5) frame = requestAnimationFrame(tick);
    };
    frame = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(frame);
  }, [target, reduced]);

  return (
    <model-viewer
      ref={ref}
      src={src ?? STAGE_MODEL[stage]}
      alt={src ? "You" : `Your ${STAGE_LABEL[stage].toLowerCase()}`}
      autoplay={!reduced}
      animation-name={animation}
      time-scale={is_paused ? "0" : "1"}
      camera-controls={false}
      disable-zoom
      interaction-prompt="none"
      /* On a card the camera stands back far enough that the crest clears a
         round crop; "auto" frames the model edge to edge. */
      camera-orbit={is_walker ? "0deg 62deg auto" : "0deg 78deg 3.2m"}
      max-camera-orbit="Infinity 180deg 20m"
      field-of-view="28deg"
      environment-image="neutral"
      exposure="1.05"
      shadow-intensity="1"
      shadow-softness="0.7"
      loading="eager"
      style={{
        display: "block",
        width: is_fill ? "100%" : size,
        height: is_fill ? "100%" : size,
        pointerEvents: "none",
        "--poster-color": "transparent",
        "--progress-bar-height": "0px",
      } as CSSProperties}
    >
      {/* The flat sticker stands in until the .glb is in — the pot used to be
          blank for a second and a half on a cold load. The trainer gets its
          own still: the egg in its place read as the wrong character. */}
      <img
        slot="poster"
        src={src === TRAINER_MODEL ? TRAINER_POSTER : stage_sticker[stage]}
        alt=""
        aria-hidden="true"
        style={{ width: "100%", height: "100%", objectFit: "contain" }}
      />
    </model-viewer>
  );
}
