/**
 * The walker's character — egg → sprout → sapling → tree.
 *
 * The stages are the ones asked for on the record (`1:05:55` egg → seedling →
 * tree), and the rule at `1:08:20` is that absence changes how it *looks*
 * without taking progress away. That is why `vigor` and `stage` are separate
 * props: vigor droops the leaves and greys the crown when nobody has walked in
 * a while, and it is fully recoverable by walking again. Stage only ever rises.
 *
 * The art is the Magisphere stage sticker (09-23) — the Sprout seed, seedling,
 * sapling and tree from the codex sticker set in `asset/magi`, the same faces
 * the HUD, dock and marketing use. It replaced hand-drawn ellipses that shared
 * nothing with the brand. Vigor now greys the sticker instead of drooping
 * drawn leaves; the rule it serves (`1:08:20`) is unchanged.
 *
 * Why this is SVG and not a `.glb` yet
 * -----------------------------------
 * The 09-03 spec adopted 3D via a self-hosted `<model-viewer>` for exactly this
 * character. The stage models now exist (`public/model/character-*.glb`,
 * generated by `script/build-character-model.mjs`) and are viewable in the
 * model gallery, but the viewer is not wired into the app bundle: T4.1/T4.2
 * (the self-hosted `<model-viewer>` dependency and the hard 320 kB gzipped JS
 * ceiling with a committed build check) is its own task and has not landed. So
 * the character is drawn with the depth cues that actually sell volume on a
 * screen: a lit side and a shaded side on every mass, a contact shadow that
 * anchors it to the ground, and a slow idle bob.
 *
 * It also billboards. On the raked map the ground plane is rotated in 3D, and
 * this counter-rotates by the same pitch, so it stands UP out of the map the
 * way a Pokémon GO avatar does rather than lying flat on it like a sticker.
 * That upright-against-a-tilted-ground read is most of what makes the view feel
 * 3D, and it costs no bundle.
 *
 * `CHARACTER_MODEL_SLOT` names the authored `.glb` files (built by
 * `script/build-character-model.mjs`, viewable in the model gallery). T4.1 has
 * landed: `src/character-model.tsx` renders them through a self-hosted
 * `<model-viewer>` (lazy chunk), and this SVG stays as its Suspense fallback
 * and as the map billboard.
 */

export const CHARACTER_MODEL_SLOT =
  "public/model/character.glb (full tree stage) — authored; per-stage files: character-egg.glb, character-seedling.glb, character-sapling.glb, character-tree.glb. Viewer wiring (T4.1) not done yet.";

/* The growth rules live in `stage.ts`, not here: Node's type stripping cannot
   load a `.tsx`, so a rule that lives beside JSX is a rule no test can import.
   Re-exported so callers still have one place to reach for the character. */
export {
  STAGE_AT,
  STAGE_LABEL,
  STAGE_ORDER,
  stageFor,
  toNextStage,
  type Stage,
} from "./stage.ts";
import type { Stage } from "./stage.ts";
import { STAGE_LABEL, STAGE_ORDER } from "./stage.ts";
import { eagle } from "./art";
import "./art/art.css";

interface Props {
  stage: Stage;
  /** 0..1. Low = unwalked and drooping. Never removes a stage. */
  vigor?: number;
  size?: number;
  /** Map pitch to stand up against. 0 outside the map. */
  tilt_degree?: number;
  /** Map bearing to stand up against. 0 outside the map. */
  bearing_degree?: number;
  is_idle_animated?: boolean;
  /**
   * Walking changes the animation, not the art.
   *
   * A stage is a thing you earned; a gait is a thing you are doing right now.
   * Keeping them separate is why absence can droop the leaves (`1:08:20`)
   * without ever taking a stage away.
   */
  is_walking?: boolean;
  /** Degrees clockwise from screen-up. Leans into the direction of travel. */
  heading_degree?: number;
}

/** Seat the stage art in the 100×115 frame, feet on the contact shadow. */
function placed(svg: string): string {
  return svg.replace(/^<svg /, '<svg x="2" y="8" width="96" height="100" preserveAspectRatio="xMidYMax meet" ');
}

export default function Character({
  stage,
  vigor = 1,
  size = 92,
  tilt_degree = 0,
  bearing_degree = 0,
  is_idle_animated = true,
  is_walking = false,
  heading_degree = 0,
}: Props) {
  const v = Math.max(0, Math.min(1, vigor));
  /* Absence greys the sticker toward a tired olive and walking brings it back;
     it never changes which stage is drawn. */
  const tired = v < 1 ? `saturate(${0.35 + 0.65 * v}) brightness(${0.92 + 0.08 * v})` : undefined;
  /* Grown stages sway from the root; the seed only bobs. */
  const sway = stage === "egg" ? undefined : `yc-sway ${4.2 + STAGE_ORDER.indexOf(stage) * 0.6}s ease-in-out infinite`;

  return (
    <div
      style={{
        width: size,
        height: size * 1.15,
        /* Billboard: undo the plane's rotations in REVERSE order, because the
           inverse of (Rx·Rz) is (Rz⁻¹·Rx⁻¹). Undoing only the pitch is what
           left the walker lying on their side as soon as the camera swung.
           Then lean into the heading — a small skew, not a turn, because the
           art is flat and edge-on it would vanish. */
        transform: `rotateZ(${-bearing_degree}deg) rotateX(${-tilt_degree}deg) rotate(${Math.max(-14, Math.min(14, heading_degree / 12))}deg)`,
        transformOrigin: "50% 100%",
        transformStyle: "preserve-3d",
        pointerEvents: "none",
      }}
    >
      <style>{`
        @keyframes yc-bob { 0%,100% { transform: translateY(0) } 50% { transform: translateY(-3.5%) } }
        @keyframes yc-sway { 0%,100% { transform: rotate(-1.6deg) } 50% { transform: rotate(1.6deg) } }
        /* A walk is a faster bob with a slight roll — enough to read as motion
           at 80 px without needing a rig or a second sprite. */
        @keyframes yc-step {
          0%,100% { transform: translateY(0) rotate(-3deg) }
          50%     { transform: translateY(-9%) rotate(3deg) }
        }
        @media (prefers-reduced-motion: reduce) {
          .yc-bob, .yc-sway, .yc-step { animation: none !important }
        }
      `}</style>
      <svg
        viewBox="0 0 100 115"
        width={size}
        height={size * 1.15}
        className={is_walking ? "yc-step" : is_idle_animated ? "yc-bob" : undefined}
        style={
          is_walking
            ? { animation: "yc-step 0.62s ease-in-out infinite" }
            : is_idle_animated
              ? { animation: "yc-bob 3.4s ease-in-out infinite" }
              : undefined
        }
        role="img"
        aria-label={`Your ${STAGE_LABEL[stage].toLowerCase()}`}
      >
        <defs>
          <radialGradient id="yc-shadow" cx="50%" cy="50%">
            <stop offset="0%" stopColor="rgba(24,38,20,0.42)" />
            <stop offset="100%" stopColor="rgba(24,38,20,0)" />
          </radialGradient>
        </defs>

        {/* Contact shadow — the single strongest cue that this sits ON ground. */}
        <ellipse cx="50" cy="105" rx={stage === "egg" ? 22 : 28} ry="6.5" fill="url(#yc-shadow)" />

        {/* Agila, inline vector (`art/svg/eagle`). Its white sticker edge is
            what keeps it legible over any sector colour. The egg rocks now and
            then; the grown eagle flaps. */}
        <g
          className={sway ? "yc-sway" : undefined}
          style={{ transformOrigin: "50px 106px", animation: is_idle_animated ? sway : undefined, filter: tired }}
        >
          <g
            className={is_idle_animated ? (stage === "tree" ? "art-flap" : stage === "egg" ? "art-wobble" : undefined) : undefined}
            dangerouslySetInnerHTML={{ __html: placed(eagle[stage]) }}
          />
        </g>
      </svg>
    </div>
  );
}
