import settings_account from "./icon/settings/account.png";
import settings_pref from "./icon/settings/pref.png";
import settings_roadmap from "./icon/settings/roadmap.png";
import settings_stage from "./icon/settings/stage.png";
import home from "./icon/home.png";
import map from "./icon/map.png";
import journal from "./icon/journal.png";
import plan from "./icon/plan.png";
import check from "./icon/check.png";
import pin from "./icon/pin.png";
import camera from "./icon/camera.png";
import close from "./icon/close.png";
import encounter from "./icon/encounter.png";
import player from "./icon/player.png";
import restricted from "./icon/restricted.png";
import canopy from "./icon/canopy.png";
import leaf_scan from "./icon/leaf_scan.png";
import locate from "./icon/locate.png";
import walk from "./icon/walk.png";
import shutter from "./icon/shutter.png";
import go_camera from "./icon/go_camera.png";
import export_ from "./icon/export.png";
import plant from "./mark/plant.png";
import narra from "./species/narra.png";
import molave from "./species/molave.png";
import katmon from "./species/katmon.png";
import mahogany from "./species/mahogany.png";
import lagundi from "./species/lagundi.png";
import dao from "./species/dao.png";
import raintree from "./species/raintree.png";
import teak from "./species/teak.png";
import balete from "./species/balete.png";
import silhouette from "./species/silhouette.png";
import game_dex from "./icon/game/dex.png";
import game_go from "./icon/game/go.png";
import game_nearby from "./icon/game/nearby.png";
import game_level from "./icon/game/level.png";
import game_lock from "./icon/game/lock.png";
import game_plan from "./icon/game/plan.png";
import game_points from "./icon/game/points.png";
import game_quest from "./icon/game/quest.png";
import game_streak from "./icon/game/streak.png";
import game_trophy from "./icon/game/trophy.png";
import empty_journal from "./spot/empty_journal.png";
import success_log from "./spot/success_log.png";
import log_sighting from "./spot/log_sighting.png";

/** Kit ink + fill — Gargar outline language, Field Guide tokens. */
export const ink = {
  line: "#1F2022",
  leaf: "#3F8A1F",
  leaf_bright: "#45C223",
  leaf_deep: "#008653",
  blue: "#57A8E8",
  blue_pwa: "#058CD6",
  mustard: "#E1A036",
  mustard_pwa: "#F6B22D",
};

export const icon = {
  home,
  map,
  journal,
  plan,
  check,
  pin,
  camera,
  close,
  encounter,
  player,
  restricted,
  canopy,
  leaf_scan,
  locate,
  walk,
  shutter,
  go_camera,
  /* `export` is a reserved word — the key is what the UI reads. */
  export: export_,
};

/**
 * Game icons — chess.com-style illustrated set generated with `codex` (gpt-image-2)
 * on a magenta key, keyed to RGBA with soft edges (09-14). Full colour on purpose:
 * these sit on the dark chess.com surfaces, not on paper like the kit glyphs above.
 */
export const game_icon = {
  dex: game_dex,
  go: game_go,
  level: game_level,
  lock: game_lock,
  nearby: game_nearby,
  plan: game_plan,
  points: game_points,
  quest: game_quest,
  streak: game_streak,
  trophy: game_trophy,
};

export const mark = {
  plant,
};

export const species_art: Record<string, string> = {
  narra,
  molave,
  katmon,
  mahogany,
  lagundi,
  dao,
  raintree,
  teak,
  balete,
  silhouette,
};

export const spot = {
  empty_journal,
  success_log,
  log_sighting,
};

/**
 * Settings-tab section art.
 *
 * Generated by `script/icon/gen-settings-icon.sh` on a magenta ground and keyed
 * by `script/icon/keyer.py`, same contract as the game set above. Every key is
 * optional on purpose: the Settings sections render headed-but-plain when a
 * piece is missing, so a half-generated set never breaks the screen.
 */
export const settings_icon: {
  account?: string;
  pref?: string;
  roadmap?: string;
  stage?: string;
  partner?: string;
  about?: string;
} = {
  account: settings_account,
  pref: settings_pref,
  roadmap: settings_roadmap,
  stage: settings_stage,
};
